//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdOrg
{
    using System;
    using System.Collections.Generic;

    public partial class Marks
    {
        public int Id { get; set; }
        public int Value { get; set; }
        public Nullable<int> UserId { get; set; }
        public int SubjectId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }

        public virtual Subjects Subject { 
            get
            {
                using(var context = new EdOrgEntities())
                {
                    Subjects subject = context.Subjects.Find(this.SubjectId);
                    return subject;
                }
            } 
        }
        public virtual Users Users { get; set; }
    }
}
